name: Build Terminal 

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
      - name: Build Application
        run: ./scripts/build-terminal.sh
